apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: vote
spec:
  type: LoadBalancer
  selector:
    app: result
  ports:
  - port: 80
    name: "result-service"
    targetPort: 80