apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  type: LoadBalancer
  selector:
    app: vote
  ports:
  - port: 80
    name: "vote-service"
    targetPort: 80